apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teste-deploy
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: teste-deploy
    spec:
      containers:
      - name: teste-deploy
        image: nigelpoulton/k8sbook:latest
        port:
        - containerPort: 80
        